default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USER'] %>
  password: "<%= ENV['DB_PASSWORD'] %>"
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aria_api_development

test:
  <<: *default
  database: aria_api_test

production:
  primary: &primary_production
    <<: *default
    database: aria_api_production
    username: aria_api
    password: <%= ENV["ARIA_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: aria_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: aria_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: aria_api_production_cable
    migrations_paths: db/cable_migrate
